### ISSUE TITLE
Please add this to the Firefox OS Marketplace

### ISSUE THREAD

**Issue by SunboX** [Gamadril/hyperion-remote#1]
Just tried your app on my Firefox OS Phone, and it works really great. Could you plese submit it to the Firefox OS Marketplace?
## Cordova for Firefox OS

https://developer.mozilla.org/en-US/Apps/Tools_and_frameworks/Cordova_support_for_Firefox_OS
## The Marketplace

https://marketplace.firefox.com/
## Submit a app here

https://marketplace.firefox.com/developers/submit/

**Comment by Gamadril** [comment]
That was my plan some time ago, I also bought real hardware for testing. I've noticed some problems with the slider on Firefox OS and already started to fix it, however never finished it. Today I read that Mozilla give up Firefox OS on smartphones... However will try to finish it and submit if they still accept new apps.
Since WebSocket support was added to hyperion some time ago, I think there is no need to use Cordova for Firefox OS. Packaging should be simple.

**Comment by SunboX** [comment]
Hey, that's great news! :smile: Would love to see it in the Marketplace.

The information about Moz giving up FxOS spread yesterday (mainly by TechCrunch and copied by others) is not correct. 

In MozLando someone has told on stage that Mozilla does not want to work with cable operators together in the future and that Mozilla is no longer selling smartphones directly. Instead, Mozilla plans to invest more commitment in supporting the community builds and porting to new platforms (TV, IoT, etc.). TechCrunch has understood something wrong and made the headline "Mozilla is giving up with Firefox OS". And everyone else has copied and re-published it at lightening speed. :smirk:  Actually the statement on stage was rather positive than negative. Maybe some wrong choice of words, too bad.

**Comment by Gamadril** [comment]
Could you check if it works on your device? It's a hosted app at the moment with the possibility to install on device and using appcache, so normally after the first start it shoul not contact the github server and use locally cached files. Just open http://gamadril.github.io/hyperion-remote/ on your device and conirm installation request.
P.S. for some reason Firefox on OSX and on Android also try to install it as local apps. Have to check how to prevent it and allow only for Firefox OS...

**Comment by Gamadril** [comment]
FF OS detection shul work correctly now

**Comment by SunboX** [comment]
Does not show a install question/message. But I can pin it as app to the homescreen. So all fine. :) 

![2015-12-13-11-52-03](https://cloud.githubusercontent.com/assets/83344/11766611/57882898-a190-11e5-8af9-109cce81ec35.png)
![2015-12-13-11-52-18](https://cloud.githubusercontent.com/assets/83344/11766614/5f01bb02-a190-11e5-9c54-a21a8c2112db.png)

**Comment by SunboX** [comment]
Btw, you can set the status bar color to dark gray if you wish :smirk: -> https://bugzilla.mozilla.org/show_bug.cgi?id=1013913

**Comment by Gamadril** [comment]
strange, tested it again in FF OS 2.0 simulator and device with OS 2.0. The confirmation appears after page is loaded in the browser.
<img width="432" alt="ffos" src="https://cloud.githubusercontent.com/assets/3903793/11767377/ee6a4442-a1ab-11e5-9400-e8c84a505019.png">

**Comment by SunboX** [comment]
K, I'm running Firefox OS 2.6-prerelease on a Nexus 4. Maybe that's the difference.

**Comment by hferee** [comment]
Installation is not proposed for me either (2.6 on flame).
User-agent is correctly matched: "Mozilla/5.0 (Mobile; rv:47.0) Gecko/47.0 Firefox/47.0"

**Comment by Gamadril** [comment]
Will try to check it. For some reason the 2.6 emulator does provide the user agent of the host and not of the simulated device and I could not find a v2.6 rom for my alcatel fire-e device for testing...

**Comment by Gamadril** [comment]
Closing that one.
R.I.P. Firefox OS - i liked you.

**Comment by SunboX** [comment]
😢
